apiVersion: v1
kind: Service
metadata:
  name: active-mq
  namespace: turbinator
  labels:
    app: active-mq
spec:
  selector:
    app: active-mq
  ports:
  - name: dashboard
    port: 8161
    targetPort: 8161
    protocol: TCP
  - name: openwire
    port: 61616
    targetPort: 61616
    protocol: TCP
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: stomp
    port: 61613
    targetPort: 61613
    protocol: TCP
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: active-mq
  labels:
    app: active-mq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: active-mq
  template:
    metadata:
      labels:
        app: active-mq
    spec:
      containers:
      - image: smaject/activemq
        name: active-mq
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 100Mi
            cpu: 250m
        volumeMounts:
        - name: active-creds
          mountPath: /home/alpine/apache-activemq-5.15.10/conf/jetty-realm.properties
          subPath: jetty-realm.properties
      volumes:
      - name: active-creds
        secret:
          secretName: creds
      restartPolicy: Always
