apiVersion: v1
kind: Service
metadata:
  name: postgis
  namespace: turbinator
spec:
  ports:
  - protocol: TCP
    port: 1432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgis
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - port: 5432
